<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DbLinq.PostgreSql\DbLinq.PostgreSql.csproj" />
      <ProjectReference Include="..\DbLinq.SqlServer\DbLinq.SqlServer.csproj" />
      <ProjectReference Include="..\DbLinq\DbLinq.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
      <PackageReference Include="System.CodeDom" Version="6.0.0" />
      <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Test\**" />
      <Compile Remove="Util\**" />
      <Compile Remove="Properties\Settings.Designer.cs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Test\**" />
      <EmbeddedResource Remove="Util\**" />
      <None Remove="Language\EnglishWords.txt" />
      <EmbeddedResource Include="Language\EnglishWords.txt" />
      <None Remove="Language\FrenchWords.txt" />
      <EmbeddedResource Include="Language\FrenchWords.txt" />
      <None Remove="Language\GermanWords.txt" />
      <EmbeddedResource Include="Language\GermanWords.txt" />
      <EmbeddedResource Remove="Properties\**" />
      <None Remove="Properties\Settings.settings" />
      <None Update="App.config">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Test\**" />
      <None Remove="Util\**" />
    </ItemGroup>

</Project>
